version: 2
jobs:
  build:
    working_directory: ~/portfolio

    steps:
      - checkout

      - run:
          name: SSH and Deploy
          command: |
            ssh -o "StrictHostKeyChecking=no" root@reivhax.me -t "cd /opt/portfolio;bash pull.sh"
